### ISSUE TITLE
How to check mars/sim from a different repository

### ISSUE THREAD

**Issue by Rauldg** [rock-simulation/simulation-package_set#20]
Hello, 

I made a fork of rock-simulation/mars and I would like to check from this repository in my project installation, in particular I want to check the core (simulation/mars/sim).

I tried with this line in my autoproj/overrides.yml 
```    
- simulation/mars/sim:                                                      
        github: envire/mars.git                                                 
        branch: rock-rc                                                         
``` 
but it continues checking out from rock-simulation. How should then this override be done? 

I am confused with the sources.yml of this package set. I guess that somehow what I want is incompatible with these lines.
```
    - simulation/*:
        github: rock-simulation/mars.git
        branch: $ROCK_FLAVOR
```

Thanks in advance!

**Comment by goldhoorn** [comment]
Try to check out:
- simulation/mars (because this is the main repro the other ones are 
sub-directories)
if this does not work use the wild card too
- simulation/mars/*

by the way, do not use the rock-rc this branch will removed soon, either 
use a commit id or the stable flavor instead.

Best,
Matthias



On 09.06.2015 11:39, Raúl Domínguez wrote:
>
> Hello,
>
> I made a fork of rock-simulation/mars and I would like to check from 
> this repository in my project installation, in particular I want to 
> check the core (simulation/mars/sim).
>
> I tried with this line in my autoproj/overrides.yml
>
> |- simulation/mars/sim:
>          github: envire/mars.git
>          branch: rock-rc
> |
>
> but it continues checking out from rock-simulation. How should then 
> this override be done?
>
> I am confused with the sources.yml of this package set. I guess that 
> somehow what I want is incompatible with these lines.
>
> |     - simulation/*:
>          github: rock-simulation/mars.git
>          branch: $ROCK_FLAVOR
> |
>
> Thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-simulation/simulation-package_set/issues/20>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by Rauldg** [comment]
`- simulation/mars/*` Works. 

`- simulation/mars` provides same result as `- simulation/mars/sim:` It checks out from rock-simulation

Thanks!

**Comment by Rauldg** [comment]
I just realized that by setting the override (in autoproj/overirrides.yml) to `-simulation/mars/*` I run in another problem.
`simulation/mars-plugins/multisim_plugin` contains now the mars library instead of what it should contain.

```
simulation/mars-plugins/multisim_plugin (rock-rc) $ git remote -v
autobuild	git@github.com:/envire/mars.git (fetch)
autobuild	git@github.com:/envire/mars.git (push)
```

**Comment by goldhoorn** [comment]
From which package set did you got this, multisim is not part of rock itself. I assume the package set which defined the multisim-plugin has a buggy source.yml

**Comment by Rauldg** [comment]
That one comes from the package set of the limes project. They have 

```
    - simulation/*:
      github: rock-simulation/mars.git
      branch: $ROCK_FLAVOR

    - simulation/entity_generation/*:
      type: git
      url: $SPACEGIT_ROOT/mars/entity_generation.git
      push_to: $SPACEGIT_PUSH_ROOT/mars/entity_generation.git
      branch: $ROCK_FLAVOR

    - simulation/mars-plugins/multisim_plugin:
      type: git
      url: $SPACEGIT_ROOT/mars/$PACKAGE_BASENAME.git
      push_to: $SPACEGIT_PUSH_ROOT/mars/$PACKAGE_BASENAME.git
      branch: gitorious
```

Is  the entry ` - simulation/mars-plugins/multisim_plugin:` correct?
